# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Blog
      path: entries/
    - label: Calendar
      path: events/
    - label: Discussions
      path: discussions
    - label: Merchandise
      path: products
      class: last
members:
    - label: Profile
      path: /auth/profile/edit
      class: first
    - label: My Card
      path: /auth/card
    - label: Notifications
      path: /auth/notifications
    - label: Messages
      path: /auth/messages
    - label: Orders
      path: /auth/orders
      class: last
